export * from "./resource";
export * from "./route";
export * from "./start";
export * from "./use";
export * from "./when";
import { AllowCorsOptions } from "../middleware/allow-cors";
import { ConnectMiddleware } from "../middleware/connect";
import { SessionOptions } from "../middleware/parse-session";
import { Credentials } from "../middleware/require-authorization";
import { ValidationOptions } from "../middleware/validate-body";
export declare function allowCors(options: AllowCorsOptions): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function connect(middleware: ConnectMiddleware): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function exposeAllErrors(): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function parseAuthorization(): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function parseBody(): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function parseQuery(): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function parseSession(options: SessionOptions): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function requireAuthorization(realm: string, credentials: Credentials): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function requireHost(...hosts: string[]): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function requireTLS(): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function validateBody(options: ValidationOptions): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
export declare function validateContentType(expected: string): (object: any, key?: string | undefined, descriptor?: PropertyDescriptor | undefined) => void | PropertyDescriptor;
